### ISSUE TITLE
建议：加入nest-cli.json配置

### ISSUE THREAD

**Issue by CloudWoR** [ArcherGu/fast-vite-nestjs-electron#10]
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "main/src"
}
我在项目中加入了nest-cli.json文件，配置如上，这样可以使用nest-cli命令来生成对应的模块，不过我尝试使用nest new app的时候，依然报错了，希望可以增加对nest-cli的支持就更棒了。

**Comment by ArcherGu** [comment]
nest-cli 生成模块应该是没有问题的，主要是 nestjs 默认的目录结构和我的目录结构不同，所以你看看是不是需要配置下。
