### ISSUE TITLE
打包后无法运行

### ISSUE THREAD

**Issue by CloudWoR** [ArcherGu/fast-vite-nestjs-electron#12]
兄弟，我又来打扰你了😁😁😁
我的项目在开发模式下运行没什么问题，但是打包后就无法执行了，也不报错，这是啥原因？

**Comment by ArcherGu** [comment]
无法执行是什么意思？有什么现象吗？你有没有在 main 进程里使用 “import type { *** } from ***” 之类的语法？

**Comment by CloudWoR** [comment]
就是打包后，点击fast-vite-nestjs-electron.exe没反应，也不报错，electron的主进程基本没改动过，只是添加了一下vue的devtools插件。我把项目传到仓库了，您帮我看看。
https://github.com/CloudWoR/AutoPrinterServer.git

**Comment by CloudWoR** [comment]
能不能帮我开发一个项目框架出来，我支付你报酬？我欠的学习债可以从你这还吗？😂🤣🤣🤣😂😂

**Comment by ArcherGu** [comment]
你看一下你的项目中`/src/main/configure/configure.load.ts` 中的 `const CONFIG_DATABASE = 'configure/database.yaml';`，这个路径存在问题，你打包以后是将整个 assets 放到 resources 下的，路径需要带上 `/assets`。

**Comment by ArcherGu** [comment]
> 能不能帮我开发一个项目框架出来，我支付你报酬？我欠的学习债可以从你这还吗？😂🤣🤣🤣😂😂

我的收费可不低哦。

**Comment by CloudWoR** [comment]
哈哈哈，你说嘛，我看看能不能承受。

**Comment by CloudWoR** [comment]
主要想请你做一个项目的架构，我按照你搭起来的架子去完善业务功能。

**Comment by CloudWoR** [comment]
顺便也学习一下企业级架构的设计思路，我欠缺的东西实在是太多了。

**Comment by ArcherGu** [comment]
这个“企业级”太难定义了，我觉得你完全可以在我这个模板框架下填充你的业务啊，没必要重新搞一个吧。
