### ISSUE TITLE
import.meta.globEager does not support

### ISSUE THREAD

**Issue by wcldyx** [ArcherGu/fast-vite-nestjs-electron#13]
在main文件夹下,nest服务中不支持支持按规则导入文件 import.meta.globEager('./modules/**/**.entity{.ts,.js}')

**Comment by ArcherGu** [comment]
Hi, 你好，nest 在主进程中，虽然我这里写了一个 vite 插件来转译 electron main 的部分，但是这个转译是我用 esbuild 额外写的，所以实际上没有经过 vite 里的转换，因此 import.meta.globEager 这种 vite 提供的功能就没有了。

至于如何支持，我最近有点忙，暂时应该没有时间来增加这个功能了。如果你着急的话可以尝试这自己修改下我里面的那个 vite 插件，让代码先经过 vite 的转译，然后再通过 esbuild，理论上这样就能支持了。
