### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by CloudWoR** [ArcherGu/fast-vite-nestjs-electron#15]
如何把nestjs整合进quasar formwork里面呀？

**Comment by undancer** [comment]
我觉得，quasar有vite插件，nestjs也可以用vite打包。所以二者一结合应该就妥了。

**Comment by ArcherGu** [comment]
我不是很理解你的需求，quasar是一个vue基础上的前端框架，为啥要把nestjs这种后端放进去？

如果你是纯粹的前后端分离项目，那就分开来。如果你想像以前一样用后端写模板，nestjs也是支持的，你在模版前端引入 quasar就行了。
