### ISSUE TITLE
怎么加密main里面的代码啊，或者加密app.asar

### ISSUE THREAD

**Issue by LiFuHai1106** [ArcherGu/fast-vite-nestjs-electron#176]
怎么加密main里面的代码啊，或者加密app.asar。https://github.com/alex8088/electron-vite有import { bytecodePlugin } from 'electron-vite'可以加密，但我用electron-vite引入nestjs后启动报错，不知道fast-vite-nestjs-electron能否加密源代码

**Comment by ArcherGu** [comment]
当然可以加密代码哦，这个和electron没有关系，和你这个 `electron-vite` 也没有关系，就是常规的 node.js 代码加密。[vite-plugin-doubleshot](https://github.com/Doubleshotjs/doubleshot/tree/main/packages/plugin-vite) 提供了一个 `afterBuild` 的钩子，你可以在里面对转译后的代码进行加密，而加密就是用 nodejs 的一个加密库 [bytenode](https://github.com/bytenode/bytenode)。
vite.config.ts:
```ts
import { join } from 'path'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { VitePluginDoubleshot } from 'vite-plugin-doubleshot'
import { compileFile } from 'bytenode' // install bytenode, and import
import { writeFileSync } from 'fs'

// https://vitejs.dev/config/
export default defineConfig({
  root: join(__dirname, 'src/render'),
  plugins: [
    vue(),
    VitePluginDoubleshot({
      type: 'electron',
      main: 'dist/main/index.js',
      entry: 'src/main/index.ts',
      outDir: 'dist/main',
      external: ['electron'],
      electron: {
        build: {
          config: './electron-builder.config.js',
        },
        preload: {
          entry: 'src/preload/index.ts',
          outDir: 'dist/preload',
        },
      },
     // hook
      afterBuild: async () => {
        await compileFile({
          filename: './dist/main/index.js',
          output: './dist/main/main.jsc',
          electron: true,
        });

        writeFileSync('./dist/main/index.js', "require('bytenode');require('./main.jsc')");
      },
    }),
  ],
  resolve: {
    alias: {
      '@render': join(__dirname, 'src/render'),
      '@main': join(__dirname, 'src/main'),
    },
  },
  base: './',
  build: {
    outDir: join(__dirname, 'dist/render'),
    emptyOutDir: true,
  },
})

```

**Comment by zmcode** [comment]
解决了吗, 我这边启动也是会报错, 很多包都没有下载成功
![image](https://github.com/ArcherGu/fast-vite-nestjs-electron/assets/48686959/f47ee32c-a3b9-4ed6-ba68-b6a99ebde031)

**Comment by ArcherGu** [comment]
@zmcode 你是什么问题？详细描述一下，有没有样例 repo

**Comment by zmcode** [comment]
> @zmcode 你是什么问题？详细描述一下，有没有样例 repo

我的项目跟题主一样, 使用的是[electron-vite](https://github.com/alex8088/electron-vite), 然后用你的nest代码, 但是我发现我使用electron-vite的加密方法: bytecodePlugin 就会报很多依赖没有安装, 不知道是不是转换成字节的时候, 需要别的依赖, 我尝试安装这些依赖, 但是最终还是无法生成加密后的运行文件
![image](https://github.com/ArcherGu/fast-vite-nestjs-electron/assets/48686959/b888b722-12c7-4b70-aa3c-6cfcb3fde668)


或许作者你可以尝试研究下, [这是demo](https://github.com/zmcode/nest-electron-test) 你可以测试一下
