### ISSUE TITLE
How to create multiple windows ?

### ISSUE THREAD

**Issue by michael-dm** [ArcherGu/fast-vite-nestjs-electron#187]
Hello ! Very promising project 🔥

How would you create and access different windows with `@Window` decorator ?

**Comment by ArcherGu** [comment]
Hi, multiple windows is now supported. [@doubleshot/nest-electron#47cc989](https://github.com/Doubleshotjs/doubleshot/commit/47cc989f178481c8a0f0f6479f79b200887fbe2d).

you can find the example [here](https://github.com/Doubleshotjs/doubleshot/blob/2a9585f575a52be2297d1a53a426157bd31caffc/packages/nest-electron/test/mock/src/app.module.ts#L28) and [here](https://github.com/Doubleshotjs/doubleshot/blob/2a9585f575a52be2297d1a53a426157bd31caffc/packages/nest-electron/test/mock/src/app.controller.ts#L9), 🙂.
