### ISSUE TITLE
Open Devtools is not working on Windows

### ISSUE THREAD

**Issue by pnhuyduy** [ArcherGu/fast-vite-nestjs-electron#275]
Devtools is not opening. I have to toggle manually through menu bars.
![image](https://user-images.githubusercontent.com/46210597/221364927-7253da99-d7a3-4f92-8d94-17b269218b41.png)

**Comment by ArcherGu** [comment]
Some third-party libraries may cause this problem, but it is not broken, but the loading process is somewhat hindered.

You can try:
```ts
  win.on("ready-to-show", () => {
    win.webContents.openDevTools();
  })
```

**Comment by pnhuyduy** [comment]
Thanks!
