### ISSUE TITLE
无法在项目中使用import.meta.env获取在.env文件内的环境变量

### ISSUE THREAD

**Issue by zh66966git** [ArcherGu/fast-vite-nestjs-electron#278]
无法在项目中使用import.meta.env获取在.env文件内的环境变量，在render文件内也无法获取

**Comment by ArcherGu** [comment]
你好，因为主进程不是用 Vite 转译的代码, 所以在主进程中是无法获取到 Vite 里的 `import.meta.env`。

渲染进程中是可以获取到 `import.meta.env` 的，不过你要把相关的 `.env` 文件放在 `src\render` 目录下，因为 `vite.config.ts` 中定义的 `root` 路径是这个。

这个模板，看上去虽然是利用 Vite 来运行，实际上渲染进程和主进程是独立分开的，渲染进程依然用 Vite，但是主进程只是用 Vite 启动了一下而已，内部的实现是独立写的。你可以参考一下我的另外一个模板：[@doubleshot/template-vue-nest](https://github.com/Doubleshotjs/template-vue-nest)
