### ISSUE TITLE
请教一个关于微服务的问题

### ISSUE THREAD

**Issue by CloudWoR** [ArcherGu/fast-vite-nestjs-electron#362]
我需要在fast-vite-nestjs-electron项目中，使用nestjs的微服务功能，请问如何配置vite及其他配置文件，来做到能同时编译所有经过nest g app app-name命令创建的微服务，并且软件打开时，所有服务同时启动？

**Comment by ArcherGu** [comment]
"微服务"，"所有服务同时启动"，我可以理解为这是一个混合应用吗？也就是说你的客户端（electron）在打开时，除了渲染进程，主进程，还需要顺带在后台唤醒一些其他的微服务。

如果是上述这种，其实是不建议用这个模板开发的，可以尝试使用这个：[Doubleshot](https://github.com/Doubleshotjs/doubleshot)，另外可以参考基于此的两个模板：
- https://github.com/Doubleshotjs/template-vue-nest
- https://github.com/Doubleshotjs/template-nestjs-microservices

上面的第一个模板，其渲染进程和主进程可以拆分成两个独立的项目（monorepo形式），然后通过 doubleshot 最终构建出electron客户端。第二个模板是使用 doubleshot 构建的nestjs微服务项目，根据你的需求，可以参考其构建部分。

至于启动的思路，则可以考虑让electron的主进程来调用nodejs api，比如 child_process 来唤醒后台的微服务。

**Comment by CloudWoR** [comment]
我开发过程中，遇到许多IO密集型的业务，已经导致主进程阻塞了，考虑使用web workers或者nodejs的原生子进程来实现，但是几次尝试都失败，才考虑使用微服务的方式，但是看了一下您这个模板的启动步骤，发现想要一次开启多个nestjs的微服务甚至自动管理微服务的创建和启动不太容易实现。这两天我在考虑这样一个建议：本身您这个模板就集成了nestjs的大量能力，而且nestjs也是主要用来开发后端的框架，假如可以将pm2也集成进来，是不是可以做成一个开发服务器的专业模板，electron的主进程管理用来负责pm2的运行，渲染进程用来做其他微服务的运行状态显示和一些相关的交互操作。

**Comment by ArcherGu** [comment]
这个集成就需要你自己去完成了。你的主要目的还是启动多个子进程来分担业务压力，客户端只是一个入口罢了，启动客户端以后在后台唤醒其他的服务，组成一个微服务网络。至于如何实现，用什么手段，你就需要自己尝试下了。

nestjs 只是在主进程中锦上添花的东西，为了写业务的时候更加方便，逻辑更加通顺，即便没有nestjs，你也可以用上述方案来做这些。

**Comment by CloudWoR** [comment]
好的，谢谢啦。

**Comment by CloudWoR** [comment]
抱歉，又来打搅你，我去[Doubleshotjs/template-vue-nest](https://github.com/Doubleshotjs/template-vue-nest)以及[Doubleshotjs/template-vue-nest](https://github.com/Doubleshotjs/template-vue-nest)库看了一下，确实可以很方便的进行开发和编译，但是还是无法理解如何实现使用template-vue-nest同时开发electron应用和nestjs的微服务，使其两者在编译的时候，同时编译打包，即让nestjs的微服务项目也如同electron项目的编译一样自动打包所有依赖，而不需要我再次去服务器install所有的依赖。

**Comment by ArcherGu** [comment]
electron 打包以后，实际上并不是像前端那样进行了所谓的捆绑（即将需要的代码都转译在一起，此后可以脱离 node_modules）。目前 doubleshot 使用的是 electron-builder 进行打包，它会自动将 package.json 中的执行依赖 (dependencies) 放入到最终结果中的 node_modules，所以electron在运行的时候也就直接从 node_modules 中加载依赖就行了。

nestjs 本质上也是一个 node.js 框架，所以构建的做法也是一样，仅转译/捆绑你自己写的代码，依赖都放在 node_modules 执行时调用。如果你觉得每次把项目部署到服务器上后需要上去 install 一次，那就在构建的最后像 electron-builder 那样把 node_modules 里的依赖包复制一份到构建结果目录下。比如你的代码构建完成后输出到 dist 目录，那就最后把 node_modules 也复制一份到 dist 目录下。并且将 dist 作为一个整体进行交付。

我个人是不建议node.js项目的交付里直接包含了 node_modules 的，因为此时的 node_modules 是构建机上对应的版本（如果构建机是 windows），然后你的部署机是 linux 依然存在大概率无法使用的情况（毕竟node.js项目的依赖多少都会包含一些原生addons），最终你还是不得不重新 install。

electron之所以将 node_modules 直接包含，因为它的目标产物是客户端，不同的客户端需要不同系统的构建机进行构建，并发布在不同的系统平台上，所以也就没有 node_modules 的兼容性问题了。

**Comment by CloudWoR** [comment]
那[Doubleshotjs/template-vue-nest](https://github.com/Doubleshotjs/template-vue-nest)项目在遇到CPU密集型业务时，想要使用多线程方式规避主线程的阻塞，是否可以类似[template-nest-microservice](https://github.com/Doubleshotjs/template-nestjs-microservices)那样，优雅的集成到一起进行开发和编译呢？能不能给一个配置模板作为参考？服务器在内网环境中，只交付dist和package.json，无法install，直接复制node_modules确实如你所说无法使用，所以想用electron来进行多线程开发。

**Comment by ArcherGu** [comment]
具体的模板我暂时没有时间帮你弄了，但是可以大概跟你说一下。

首先，你要明白无论是浏览器, node, 亦或是electron(特殊的node) 环境中，js都是单线程的（加入不考虑 worker 和 node addno 里的原生线程），所以你说的应该是创建多个进程来进行。

然后根据上面的原理，你应该准备好以下几个东西，
1. electron 的进程文件，即我们写一个最简单的 electron的程序都会由的入口文件 main.js，它负责启动 electron
2. 微服务的入口文件，根据你微服务的数量可能会有很多个，每个微服务都会是一条独立的 node.js 进程

上面的文件怎么准备？你可以认为是多个项目（一般这种我们都会用monorepo的方式进行管理），然后每个项目用构建工具（比如webpack, rollup, esbuild, 你可以用不同的工具也可以用相同的）进行构建，然后它们会产出上面的文件。

这个时候，上面的这些文件都是可以独立执行的。接着你就要利用 electron-builder 将它们一起打包进 electron 客户端中，通常我们会打包到 app.asar 这样的压缩文件中。具体的配置你可以参考[这里](https://github.com/Doubleshotjs/template-vue-nest/blob/main/electron-builder.config.js), 里面的 `files` 字段就是将你上面这些独立的项目文件放入到最终 app.asar 路径下的。

这个时候你其实已经把它们都构建在一起了，当然，对于node_modules的处理，如果你的这些文件共享一个 package.json， 那就不用处理了，electron-builder 会帮你搞定，如果你是用 monorepo，即electron/微服务们都有各自的 package.json, 那你就要整理一下，把它们需要的依赖都汇总到一个 package.json 中，让electron-builder 去读这个 package.json 来打包 node_modules。

这样，你所有的东西都在electron客户端里了。

微服务如何启动？当你打开electron客户端时，启动的只是 electron 的进程文件，你要在这个文件的代码中去根据路径依次启动微服务的进程文件，比如 child_process。

**Comment by CloudWoR** [comment]
非常感谢，我按照您给的思路，并结合template-vue-nest模板实现了如下一个demo，在根目录使用pnpm dev可以运行，但是当编译后，没有将依赖包的依赖包打包导致错误，可否指导一下？
[template-electron-nestjs](https://github.com/CloudWoR/template-electron-nestjs)

**Comment by ArcherGu** [comment]
我看了一下你的repo，依赖没有打包的问题其实已经在这个项目的 README 中写了:

> In order to use with , you'll need to adjust your to use any one the following approaches in order for your dependencies to be bundled correctly (ref: [#6389](https://github.com/electron-userland/electron-builder/issues/6289#issuecomment-1042620422)):pnpm.npmrc
>  - node-linker=hoisted
>  - public-hoist-pattern=*
>  - shamefully-hoist=true

上面三种方法选一个，一般我用第一个，在这个repo的根目录下新建一个 `.npmrc`，放上上面的第一个配置，然后重写 `pnpm i` 一下（也许需要 `pnpm i -f`），这样你在构建的时候就能把依赖的依赖都打包进去了。

**Comment by ArcherGu** [comment]
另外你在repo中的 README 的两个问题也回答一下：
第一个问题：dsr.config.ts嵌套过深，这个问题其实是你的项目结构组织有问题，你的repo其实是一个 monorepo 嵌套一个 monorepo，一般我们是不建议这样做的。尽管你的 gateway/electron两个app都属于backend，但是组织为monorepo的时候是组织成：
```
packages
├─frontend
├─electron
└─gateway
```
它们应该是平级的结构，各属于这个项目中的独立模块。这样你就只要在根目录下放一个 dsr 就行了，electron/gateway 下放dsb即可。

第二个问题：上面已经回答了，是pnpm的配置问题。

**Comment by ArcherGu** [comment]
除此之外，你这边还是存在问题的，你这样子来启动这些模块，只是开发模式下有效，生产模式下 gateway 实际上不会启动的。上面已经跟你提到了，electron项目，electron框架只会启动electron的那个 main.js，作为主进程，所以gateway作为另外一个服务，需要通过 main.js 来进行启动（可以使用 child_process，作为主进程的子进程）

所以你在项目配置时，gateway 不应该通过 dsr 来跑，dsr只要跑 electron/frontend 就行了，gateway只需要构建就行，然后让 electron里的代码去调用node子进程来启动它。

**Comment by CloudWoR** [comment]
非常感谢，有高人指点就是不一样哈。

**Comment by CloudWoR** [comment]
你好，我按照你给的思路重新修改了项目目录结构，新的项目地址：[template-electron](https://github.com/CloudWoR/template-electron.git)。运行和编译问题已经解决。但是在配置assests资源时，无从下手。
因为gateway我需要在开发模式下使用dsb dev的方式运行，并且将assests文件夹下面的yaml配置文件在dev模式下打包进入dist目录下供gateway在开发模式下使用，请问doubleshot有相应的配置可以处理静态资源吗？或者需要别的方式处理静态资源？
考虑过使用nestjs来处理静态资源，但是实践中，因为项目结构改动较大，按照官网的推荐，在nest-cli中配置了“assets”目录，使用nest start gateway方式运行，貌似webpack报错了。。。


``` sh
PS D:\project\software\Object_Pacs\US_Report_Recogniz> nest start gateway
webpack 5.88.1 compiled successfully in 4049 ms
Error: Cannot find module 'D:\project\software\Object_Pacs\US_Report_Recogniz\packages\dist\gateway\main'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```
**非常感谢百忙之中可以帮我答疑解惑。**

**Comment by ArcherGu** [comment]
你可以在 `electron-builder.config.js` 里定义。我通常是这样做的，你可以通过 electron 的 `const IS_DEV = !app.isPackaged` 来定义一个 `IS_DEV` 的静态值，然后在 `IS_DEV` 模式下，加载的路径是 a（开发模式下的资源路径）, 在 `!IS_DEV` 加载的路径是 b（生产模式下的资源路径）。

接着，你用在  `electron-builder.config.js` 里定义好构建时 a 路径要复制到哪里（即b路径）。定义的配置是`files`字段(也有一些其他的字段，不过我一般就用 files )。

**Comment by CloudWoR** [comment]
**非常感谢**，一直在钻nest-cli.json的牛角尖，按照你给的思路，我在package.json中做了如下更改：
```json
"scripts" {
  "dev": "cross-env DEV=true dsr dev",
  "build": "dsr build"
}
```
electron-builder.config.js中也把静态资源目录添加进去了，目前正常运行及编译。

**Comment by ArcherGu** [comment]
你的更改没啥问题，如何判断是开发环境还是生产环境这个反正看个人喜好，只要能准确判断就行。然后根据不同的环境进行分支处理即可。

**Comment by CloudWoR** [comment]
好的，非常感谢大佬的教导。
