### ISSUE TITLE
Can't get datasource to work inside the Doubleshot.

### ISSUE THREAD

**Issue by Acetyld** [ArcherGu/fast-vite-nestjs-electron#363]
https://github.com/Acetyld/fast-vite-nestjs-electron-datasource
I made a repo to reproduce the problem.

Normal NestJS same code no issue's.
After a solid hour of debugging i gave up =), i hope your insights give more enlightment ;p

**Comment by ArcherGu** [comment]
I cloned your repo and it looks like it's working, so are you having any problems? Please add an error log

**Comment by Acetyld** [comment]
Correct, i managed to fix it. It was typescript autofix getting wrong import see
https://github.com/Acetyld/fast-vite-nestjs-electron-datasource/commit/7ef5497db470fd3434a97e07b704ea1d5a016541 ->src/main/order/order.subscriber.ts.

Right now i paused using the package, i love NestJS and would love to use it inside Electron, i was facing issue's while launching two windows.

I manage to do this with electron-vite (one of the best Electron + Vite package imo). They have native support for multi-windows. This is without NestJS which is fine for now, i just used plain TypeORM with IPC layers.
https://github.com/Acetyld/electronnetworksqlite-

I couldt manage to get this working with doubleshot.
Also maybe it is a idea to make the Transport for electron dynamic so we can also use it in electron-vite, that would be love.y

**Comment by ArcherGu** [comment]
doubleshot supports multiple windows, as long as multiple ElectronModules are introduced. You can also add names for different windows. https://github.com/Doubleshotjs/doubleshot/tree/main/packages/nest-electron

I actually used DoubleShot to complete some internal projects, and they all worked very well, and with nestjs, it saved a lot of time.

**Comment by Acetyld** [comment]
Do you got a example?

**Comment by ArcherGu** [comment]
Controlling the loading order between different modules is a topic on nestjs, and an easy way to do this is to modify the order of arrays in imports:[].

**Comment by Acetyld** [comment]
Yhea no i mean delaying the load of typeorm until a URL is saved inside electron-store for example, i know managed to do this in a bare nestjs projet bcs its not a nestjs module
