### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by cuilonglong0422** [ArcherGu/fast-vite-nestjs-electron#366]
请问一下这个是否可以完成打包mac可安装程序

**Comment by ArcherGu** [comment]
可以，这是electron，只要你没用什么平台限制的依赖，一般都能构建到不同平台

**Comment by cuilonglong0422** [comment]
因为我尝试了一下打包生成的是windoiws 我以为你封装好了

**Comment by ArcherGu** [comment]
安装包是electron builder做的，没有特殊设置，你在什么平台上构建，就产生什么平台的安装包。

**Comment by cuilonglong0422** [comment]
好的了解了 感谢大佬解惑
