### ISSUE TITLE
添加了TypeOrm后，服务注入报错

### ISSUE THREAD

**Issue by veryws** [ArcherGu/fast-vite-nestjs-electron#42]
![微信截图_20220718193107](https://user-images.githubusercontent.com/12027678/179510571-a46729f7-995b-4040-88a4-ec4b99b63e58.png)

**服务层添加“ constructor(@InjectRepository(CWell) private readonly repository:Repository<CWell> ){}”就报错，移出就正常，提示让安装“pg-native”，但pg-native的安装，需要更多的工具，确认不支持TypeOrm嘛？**

![image](https://user-images.githubusercontent.com/12027678/179511194-98aa75a3-a493-4ef1-a220-38495f9361ba.png)

**Comment by ArcherGu** [comment]
这个是支持的，只不过这些原生的node库需要在 `vite.config.ts` -> `plugins` -> `VitePluginElectronBuilder` 中的 `external` 字段中添加进去，这样在构建的时候不会将他们也打包进去。

你在写 `nestjs` 后端或者其他 `node` 后端的时候，其实也是这样的，它们仅仅构建你写的代码，而不会将相关的引用也包含进去，这个和前端是不一样的。
