### ISSUE TITLE
contextisolation和require冲突怎么解决呀

### ISSUE THREAD

**Issue by veryws** [ArcherGu/fast-vite-nestjs-electron#45]
![微信截图_20220722124609](https://user-images.githubusercontent.com/12027678/180365353-a24593e0-bcda-4511-ac47-04c32d6f8983.png)

 webPreferences: {
          nodeIntegration: true,
          contextIsolation: true,
          preload: join(__dirname, '../preload/index.js'),
          devTools: isDev
        }
contextIsolation设为true
    开发版本：界面正常，可调用IPC方法，但不用使用require方法
    发布版本：界面空白

contextIsolation设为false
    开发版本：界面正常，不可调用IPC方法
    发布版本：界面正常，不可调用IPC方法

请问怎么解决这个问题呀

**Comment by veryws** [comment]
前端没用require，import也算嘛。请问在哪里修改呀
![789](https://user-images.githubusercontent.com/12027678/180423342-fe028fb2-bb59-4b79-83de-cbda6329b0ee.png)
![101](https://user-images.githubusercontent.com/12027678/180423386-f67e857a-b255-42ca-a935-8546fa0435f6.png)
![image](https://user-images.githubusercontent.com/12027678/180423566-410be7a3-7197-4b16-ba79-3789e1c7d6c1.png)

**Comment by ArcherGu** [comment]
你的前端部分有 `import { ipcRenderer } from 'electron'` 这样的引入，你的前端应该是和 electron 完全隔离的，所以不要直接从 electron 中引入东西。
