### ISSUE TITLE
Building gives a build without node process

### ISSUE THREAD

**Issue by Acetyld** [ArcherGu/fast-vite-nestjs-electron#465]
This also happens on template, you clone it then yarn, yarn build then execute the mac image from dist or on windows
![Screenshot 2023-09-27 at 10 38 29](https://github.com/ArcherGu/fast-vite-nestjs-electron/assets/55088242/6b69f0c6-41f0-4b87-b1a5-3ceabf72aa19)
But it doesnt regonizes anything node/nestjs related

**Comment by Acetyld** [comment]
N.v.m, something went wrong while starting NestJS i think, the TypeORM config was not correct.

But how can i debug this in production, so how can i debug the nodejs part?

**Comment by ArcherGu** [comment]
Are you using sqlite? I use TypeORM + Sqlite as my database in production and it actually works really well. You can't debug in production mode, but you can debug in development mode, just like a normal node.js application. Below is a simple configuration: 
`.vscode/launch.json`
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug with npm",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "runtimeArgs": [
        "run-script",
        "dev"
      ],
      "runtimeExecutable": "npm",
      "console": "integratedTerminal"
    }
  ]
}
```
