### ISSUE TITLE
适用场景求助

### ISSUE THREAD

**Issue by wideweide** [ArcherGu/fast-vite-nestjs-electron#608]
## 最初需求
跨平台的web应用能力扩展工具：
* 系统级的通知消息
* 本地文件监听与读写等

## 技术选型

终端安装本地web服务供浏览器页面调用扩展能力：
* express用于实现服务，后来引入nest 也不算复杂， 主要借用其模块划分及文件组织方式
* 系统级通知及窗口集成electron，兼容性好：考虑封装成一个模块，提供createWindow等方法供express路由或后端定时器使用，为页面注入与主进程通信的相关方法
* 发布方式：不同操作系统提供不同的node_modules,以源码方式发布， 升级时下载对应模块或全部源码即可 

## 遇到问题
基于 https://github.com/electron/electron-quick-start 实现了逻辑, 但发现以electron .或node ./node_modules/electron/cli.js . 可以正常运行，直接node main.js 就会提示app.*的方法TypeError: Cannot read properties of undefined (reading 'on')

通过搜索nest electron发现了这个项目，看上去刚好就是我需要的，但感觉学习曲线略有陡峭，在深入之前想咨询了解一下，还望不吝赐教：

* 看上去Doubleshot 就可以满足我的需要了: 封装后台使用的electron能力
* 是否还支持nest start的方式?
* vite没太用过，yarn build # npm run build会生成什么？发布时如何使用？是否能很方便的制作跨平台的包，还是每个操作系统各自生成？

所以[fast-vite-nestjs-electron](https://github.com/ArcherGu/fast-vite-nestjs-electron)是否适合我的需求，可以继续深入研究？

**Comment by ArcherGu** [comment]
可以先看下我之前写的一篇博客: [极速DX Vite + Electron + esbuild](https://archergu.me/posts/vite-electron-esbuild)

**Comment by wideweide** [comment]
试着跑了一下报错：

拉取仓库最新版本，pop !os (ubuntu),Node.js v18.16.1

  VITE v5.1.4  ready in 571 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
DSB 💻 Mode:  Development 
DSB 💠 Application type:  electron 
DSB ✅ Prebuild succeeded! (127.40ms)
DSB 🚦 Wait for renderer: http://[::1]:5173
/home/dlt/Source/fast-vite-nestjs-electron/node_modules/wait-on/lib/wait-on.js:131
            return throwError(Error(`${TIMEOUT_ERR_MSG}: ${resourcesWaitingFor}`));
                              ^

Error: Timed out waiting for: http-get://[::1]:5173

**Comment by wideweide** [comment]
补充一下：费了很大劲儿npm run build成功了，构建成功后的文件点击可以正常执行

上面为什么会报错呢？

**Comment by ArcherGu** [comment]
> 补充一下：费了很大劲儿npm run build成功了，构建成功后的文件点击可以正常执行
> 
> 上面为什么会报错呢？

你这个问题应该是你的网络没有开ipv6导致的，你可以在 vite.config.ts里增加配置，强制使用 ipv4
```ts
export default defineConfig({
  server: {
    host: '127.0.0.1',
  },
//...
})
```

**Comment by ArcherGu** [comment]
建议看一下这个项目真正的模板：https://github.com/Doubleshotjs/template-vue-nest

我搞这个东西的初衷是为了应付常见的一种情况，在早期阶段，我们只需要提供桌面客户端client即可。但是随着使用人数的增加，b/s变成了一个硬性需求，这个时候你可以快速的从这个桌面客户端中拆分出一个web前端，一个node.js后端。

当然，后面我发现，就算未来没有拆分b/s需求，利用nest.js出色的组织形式，可以让桌面客户端的代码架构更加合理，这个就和常规的electron项目拉开差距了。这套架构我已经在生产环境中应用过了，当然对于使用者来说基本感觉不出来什么变化，重要的是对开发者的帮助。

非常感谢你对本项目的关注。

**Comment by wideweide** [comment]
> 建议看一下这个项目真正的模板：https://github.com/Doubleshotjs/template-vue-nest
> 
> 我搞这个东西的初衷是为了应付常见的一种情况，在早期阶段，我们只需要提供桌面客户端client即可。但是随着使用人数的增加，b/s变成了一个硬性需求，这个时候你可以快速的从这个桌面客户端中拆分出一个web前端，一个node.js后端。
> 
> 当然，后面我发现，就算未来没有拆分b/s需求，利用nest.js出色的组织形式，可以让桌面客户端的代码架构更加合理，这个就和常规的electron项目拉开差距了。这套架构我已经在生产环境中应用过了，当然对于使用者来说基本感觉不出来什么变化，重要的是对开发者的帮助。
> 
> 非常感谢你对本项目的关注。

首先感谢开源分享及热情回复 ！

我没有拆分成b/s的需求，此前后端java spring cloud,前端vue；现在希望nest提供在终端计算机提供本地服务，electron提供一个壳嵌入前端页面使得看上去像是个客户端
我的初衷“跨平台的web应用能力扩展工具”，刚好就是nest+electron,这个项目恰恰就是我需要的
“利用nest.js出色的组织形式，可以让桌面客户端的代码架构更加合理”，也是我准备使用nest的一个初衷
此处再次为您分享这么好的项目点赞！

> 项目真正的模板：https://github.com/Doubleshotjs/template-vue-nest

基于本项目，已经花费了不少功夫对组件降级测试使得兼容win7/10/11/linux，需要迁移到真正模板template-vue-nest吗？
大概看了一下代码，除了运行构建的脚本有些差异，核心原理基本一致吧？

另外一个跟此项目多少有点关系的问题，就是调用系统api是否也有类似doubleshot这样的神器？napi系列的node相关插件安装配置起来还是有点麻烦
