### ISSUE TITLE
How to build for Windows using react in render?

### ISSUE THREAD

**Issue by DanielXavierJob** [ArcherGu/fast-vite-nestjs-electron#649]
Hello, I'm trying to use your project with render in react, the construction and development is 100% but I'm having difficulty building it, it builds electron but it's not adding the render, could you help me?

**Comment by ArcherGu** [comment]
I've created a react template that you can refer to, [vite-react-nestjs-electron](https://github.com/ArcherGu/vite-react-nestjs-electron)

This set of templates actually doesn't have too many restrictions on the frontend part, as long as the frontend template provided by Vite is theoretically applicable.

**Comment by DanielXavierJob** [comment]
Thanks!
