### ISSUE TITLE
No handler registered for 'msg'

### ISSUE THREAD

**Issue by ghostxbh** [ArcherGu/fast-vite-nestjs-electron#698]
#### Q: 
Using your side of the wrapper library, set up ipc communication failed to register Handle

#### Log:
```log
Error occurred in handler for 'msg': Error: No handler registered for 'msg'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82920)
    at WebContents.emit (node:events:518:28)
    at WebContents.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by ghostxbh** [comment]
There is no problem in downloading and using your warehouse demo. Through your ipc communication, my request is invalid

**Comment by ArcherGu** [comment]
Can you provide a demo repository

**Comment by ghostxbh** [comment]
Thank you. I have solved the problem
