### ISSUE TITLE
大佬 请教个问题

### ISSUE THREAD

**Issue by renjietan** [ArcherGu/fast-vite-nestjs-electron#772]
大佬 我集成sqlite3的时候 各种报错  能出一个sqlite3的版本吗。。感谢啦

**Comment by ArcherGu** [comment]
你报什么错误呢？首先可以明确sqlite是可以集成的。

**Comment by renjietan** [comment]
大佬 请问在npm install的时候  报各种版本依赖的问题，  我确信package.json 我没有更新过，怀疑是nodejs的版本的问题，您这边用的是哪个版本的node呢

**Comment by renjietan** [comment]
> 你报什么错误呢？首先可以明确sqlite是可以集成的。

大佬方便加一下微信吗，，，

**Comment by ArcherGu** [comment]
> > 你报什么错误呢？首先可以明确sqlite是可以集成的。
> 
> 大佬方便加一下微信吗，，，

我加你QQ了
