### ISSUE TITLE
新功能提议, 关于功能规划的提问

### ISSUE THREAD

**Issue by eamd-wq** [ArcherGu/fast-vite-nestjs-electron#783]
最近自己想做一款桌面应用练手，看了一圈发现了这个不错的项目；不知作者是否有对此项目的长期规划，添加更丰富的功能；
如果能再集成一些开箱即用基础的功能就更好了，例如Electron-egg中的 本地日志、数据库、任务等功能；

**Comment by ArcherGu** [comment]
暂时不会添加这些，至少在这个模板里不会。

因为这个模板集成了electron和nestjs，要求开发者有较高的应用开发能力，横跨客户端开发和nodejs后端开发。我相信能同时在这两块领域有积累的开发者肯定有自己的集成能力。特别是nestjs的模块式插件，其生态和扩展性是很强的，而且很多都已经在它们的官方文档里写了。

所以我只想提供一个基础的模板，做了electron和nestjs的通信方案，更多的是提供一个思路给想更加深入做更加高阶架构的开发者。

**Comment by ArcherGu** [comment]
你提到的这些功能，在nestjs的生态里都能找到对应的模块插件，很多还是官方的，直接集成即可了。

我自己在生产环境中都是集成过这些的。

**Comment by eamd-wq** [comment]
前后端开发和桌面开发在开发思维上有着些许差异，我比较熟悉nestjs和前端开发，只是刚接触Electron，想要找寻一些最佳实践；有没有推荐的
我期望有一个monorepo风格，支持 nestjs ts 完全使用 esm 并且有着完善的eslint规则的脚手架，自己做肯定要踩不少坑；
所以有没有推荐的 [手动可怜]
Electron-egg的demo还需要内外下载两次依赖，而且主进程只支持js，个人觉得这并不是我想要的最佳实践；
所以有没有推荐的 [手动可怜]

**Comment by ArcherGu** [comment]
https://github.com/Doubleshotjs/template-vue-nest

**Comment by eamd-wq** [comment]
3Q
