### ISSUE TITLE
静态资源配置

### ISSUE THREAD

**Issue by CloudWoR** [ArcherGu/fast-vite-nestjs-electron#9]
nest的静态资源如何处理？比如yaml文件，nestjs中使用nest-cli.json文件配合webpack来生成，您这个项目用的vite构建，我不知道如何设置。能指导一下吗？谢谢。

**Comment by ArcherGu** [comment]
静态文件可以通过 electron-builder 的配置项 [extraResources](https://www.electron.build/configuration/contents#extraresources) 来进行处理，在 `electron-builder.config.js` 文件里配置。

至于 webpack 的构建也是可以的，因为这个项目里主进程的本质是使用 vite 内部的 esbuild 对 electron 主进行进行转译，从 TS -> CJS，然后用 electron builder 进行构建。所以你使用 webpack 也是相同的道理，把主进程从 TS 转译到 CJS 就可以了。

**Comment by CloudWoR** [comment]
extraResources: [
        {
            from: "src/main/assets/",
            to: "assets/",
        }
    ],
搞定了，谢谢。
