### ISSUE TITLE
生成32位程序报错

### ISSUE THREAD

**Issue by veryws** [ArcherGu/fast-vite-nestjs-electron#90]
![image](https://user-images.githubusercontent.com/12027678/188253070-5ed260b2-7cf6-49c9-9144-cb950818c0ae.png)
![image](https://user-images.githubusercontent.com/12027678/188253083-ee8890ba-1e5c-4e5e-b54f-0d46cd765b23.png)

就是有生成32位需求，生成后报错了，请问怎么配置下啊

**Comment by ArcherGu** [comment]
你好，你是不是有用 bytenode 加密你的主进程代码？

**Comment by veryws** [comment]
![image](https://user-images.githubusercontent.com/12027678/188532169-f9ac089c-b317-470b-821c-235bb2feb6da.png)
主进程没动，就改框架上面的东西
生成win64位可以，生成win32运行就报错了

**Comment by ArcherGu** [comment]
看你的目录结构，感觉还是我以前的版本，你看下 vite.config.ts 文件，里面是不是用到了 bytenode，我以前写的一个版本里放了这个玩意，现在已经去掉了，选择权交给用户
