### ISSUE TITLE
关于依赖库版本更新的请教

### ISSUE THREAD

**Issue by eamd-wq** [ArcherGu/fast-vite-nestjs-electron#904]
请教一下，项目依赖库的版本更新是人工操作的还是自动化流水线做的

**Comment by ArcherGu** [comment]
你是说这个仓库吗？我用的是github提供的更新机器人[Renovate](https://github.com/marketplace/renovate)，它会自动来更新依赖，不过这个东西最好配合一套基础的ci/cd，比如lint/test之类的，这样过了ci/cd后才允许自动合并。

**Comment by eamd-wq** [comment]
好的 感谢 我去研究下
